addons:
  postgresql: "9.5"
before_install:
   - sudo /etc/init.d/postgresql stop
   - sudo apt-get -y remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4
   - sudo apt-get -y install postgresql-9.5
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3
install: "true"
language: erlang
otp_release:
  - 19.1
  - 18.3
script:
  - ./rebar3 do xref,ct,dialyzer,coveralls send
